language: node_js
node_js:
  - '8'
  - '10'
  - '11'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "N0S3GLHTpmK0QyMbP7g7idL+plJHabtZ7/nKFcFobErOkcLVKh1LS2nlQFcDEH3HGkozAnXtVgFfGzPPAsE21XzZ2pfelTv/ov2hXJz9XXb0OxIdnS0IrlRXYVjz7shOeCaOd6pVe3/ao8HX8PVJlvBEDwc9kNzb4VlX4Mo6IKyov78MY6wGOM3aLXNF4WNtnCpf6GuKuRrhx5HdD9yUbgCJDCIO/W6hJUFioXZdlIwXwW10fVeiERs10v9+ymQOX0no7SwBrAkuhX3/50M/19VcCgG3hrSA7XKxoDSeAtS8OQBb9veHkHaGM1hbU6eritkTLiZs7ZhSC4lfHaiKhc8TY1l1SSqrU5u8Z7NrEDb8ibUIh/h4GqOyQzHt+e9BzCIlre76dKAAC0TN0Nvm/JahY18RPTnCERCulNvtvP/k/YWJl3TAS3WTbW4yq0VXu8F+SHNwCJGTDlyLetp2kioSGedx6Siw0/ZiURQ4iYC5jgRgtHUss1z2vuXMDMdBE9uLQxMe+h6+NxiH9eHuIBX6e8oU++UMKZ2BBO7H3hrAnmSu9Lrg5HqHImX81crTdk4I0L0iI2PyJ82v3soyrlxYcij6ik8HLXw+q9WCjXW5OFeMsolg2h54Rb4+PFvlSBm93+prradDV+W7zVpU4I2D3ImWIhBTT2ET2/Ewsl4="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/jupiter-integration-jamf
    node: '8'
