language: node_js
node_js:
  - '12'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "fmYX8jb/vflyzGkHc2gpfTVzrXaXhktkFHP33+ECowzniuppHwpTPdwMON6czcxmsRge1uKv1fw61U+uRyzBsXV9v/yuot3c7bakga13tKTNpKHt/XV7TIKHtOtr0IffCOeQ8oREBIyHdc/8rCOSQJmtnj67N55a745PTgYaZlpU1nIsdAL3/miiTOR5s+6Ro0eCOUFKprKFAHFoEBbykm3EbokK4gH0DAfw/seacQtxLWQnTpIeTqw3TVhPf7rc3tnc2syThaHNR13kA/75W/GqxYtncBwyRM2dXU2itXAZ2GgOzPhDmDmpPCz+QC0VlU4q/6KcRlKJywEc7JDF648mj+iROYgM/A1pjAbKN1ZxOZQ2qTTf0Y3X6v4V2w4Hbchiw3X/IOu/Rf7QinUD4G4TwmxVTEK0imC1X/oEPf9Cqchd7fZHWJwOEqTAzaVNCPMsm6X1brzXbMlAoDKGup8R4Q6lIYU26ud/p8q2T/REZGgmT0NGpHVxM8s33iC9fSBdr3dm2PuOtrPcuUJGj96RgsOFD1VpZYD4+GineCsPYn+EgkcrTde+ScGTWXgJMesz2Oy01WIlLmmU8RsodrVDS/XfNBH8nKiuj2YVXPKna7wdy7vd6rwu8zK9rOV25YS2TnjqZjhhbSYf0xjMpeQnHS7IgqMC+abWsyTiUWw="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-jamf
    node: '12'
